require:
  - rubocop-rspec

Style/Documentation:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - bin/**/*
    - vendor/**/*
    - build/**/*
    - gemfiles/**/*
    - spec/fixtures/files/**/*

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '*.gemspec'
    - spec/**/*.rb
    - '**/*.rake'
    - doc/**/*.rb

# MFA is not yet enabled for our gems yet.
Gemspec/RequireMFA:
  Enabled: false

# We stay with the original Ruby Style Guide recommendation.
Layout/LineLength:
  Max: 80

# Document all the things.
Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

# It's a deliberate idiom in RSpec.
# See: https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# Because +expect_any_instance_of().to have_received()+ is not
# supported with the +with(hash_including)+ matchers
RSpec/MessageSpies:
  EnforcedStyle: receive

# Because nesting makes sense here to group the feature tests
# more effective. This increases maintainability.
RSpec/NestedGroups:
  Max: 4

# Disable regular Rails spec paths.
RSpec/FilePath:
  Enabled: false

# Because +enqueued_jobs+ is a method not a memoized variable,
# so when first evaluated it won't change.
RSpec/ExpectChange:
  Enabled: false

# Because we heavily rely on memoized helper
# procs/lambdas and other stuff.
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# This looks like a false/positive. We test explicitly
# with the +expect+ mock call.
RSpec/StubbedMock:
  Enabled: false

# NOTE: Remove this when Ruby 2.7 is the minimum version.
# See: https://github.com/rubocop/rubocop/pull/11177
Style/ObjectThen:
  Enabled: false

# NOTE: Remove this when Ruby 2.7 is the minimum version.
# Because otherwise +.pretty_inspect+ is not defined. (+require 'pp'+)
Lint/RedundantRequireStatement:
  Enabled: false
